"""
sample_data.py
===============
Illustrative, clearly-fictional sample values so the app can be explored
immediately without hand-typing ~40 fields per asset first. NOT live data --
values are round, plausible placeholders for demonstration only. Loaded via
the "Load illustrative sample data" button in the sidebar.
"""

from datetime import date

from data_model import RawValue
from metric_catalog import FIELD_DEFS

TODAY = date.today().isoformat()

# asset -> {field_key: (value, previous_value_or_None)}
SAMPLE_VALUES = {
    "USD": {
        "current_policy_rate": (4.25, None), "expected_rate_3m": (4.00, None),
        "expected_rate_6m": (3.75, None), "expected_rate_12m": (3.50, None),
        "policy_stance": ("Hawkish", None), "forward_guidance_tone": ("Balanced", None),
        "yield_2y": (3.90, 4.05), "yield_10y": (4.20, 4.10),
        "cpi_yoy": (2.9, 3.1), "inflation_target": (2.0, None), "wage_growth": (4.0, None),
        "inflation_expectation_10y": (2.3, 2.2),
        "unemployment_rate": (4.1, 4.2), "employment_growth_yoy": (1.2, None),
        "gdp_yoy": (2.4, 2.1), "retail_sales_yoy": (2.8, None),
        "manuf_pmi": (49.5, 48.8), "services_pmi": (53.2, 52.5), "consumer_confidence": (104.0, None),
        "current_account_pct_gdp": (-3.2, None), "trade_balance_trend": ("Worsening", None),
        "risk_environment": ("Neutral", None), "vix_level": (16.0, 14.5),
        "safe_haven_demand_signal": ("Moderate", None), "geopolitical_stress_level": ("Medium", None),
        "net_position_pct_oi": (18.0, None), "position_percentile": (62.0, None), "position_change_4w": (5.0, None),
        "reer_deviation_pct": (8.0, None),
        "fiscal_balance_pct_gdp": (-6.5, None), "fiscal_trend": ("Expansionary", None), "debt_to_gdp": (123.0, None),
        "balance_sheet_trend": ("Contracting", None),
        "cpi_surprise": ("In-line", None), "gdp_surprise": ("Beat", None),
        "employment_surprise": ("Beat", None), "pmi_surprise": ("In-line", None),
        "surprise_policy_relevance": ("High", None),
        "priced_rate_change_12m_now": (-0.75, None), "priced_rate_change_12m_1m_ago": (-0.50, None),
        "geopolitical_impact": ("Neutral", None), "geopolitical_confidence": ("Medium", None),
    },
    "EUR": {
        "current_policy_rate": (2.15, None), "expected_rate_3m": (2.00, None),
        "expected_rate_6m": (1.90, None), "expected_rate_12m": (1.90, None),
        "policy_stance": ("Neutral", None), "forward_guidance_tone": ("Dovish", None),
        "yield_2y": (2.05, 2.15), "yield_10y": (2.55, 2.50),
        "cpi_yoy": (2.1, 2.3), "inflation_target": (2.0, None), "wage_growth": (3.2, None),
        "inflation_expectation_10y": (2.0, 2.0),
        "unemployment_rate": (6.3, 6.2), "employment_growth_yoy": (0.6, None),
        "gdp_yoy": (0.9, 0.7), "retail_sales_yoy": (1.1, None),
        "manuf_pmi": (48.0, 47.4), "services_pmi": (51.0, 50.6), "consumer_confidence": (96.0, None),
        "current_account_pct_gdp": (2.8, None), "trade_balance_trend": ("Stable", None),
        "risk_environment": ("Neutral", None), "vix_level": (16.0, 14.5),
        "net_position_pct_oi": (10.0, None), "position_percentile": (55.0, None), "position_change_4w": (-2.0, None),
        "reer_deviation_pct": (-4.0, None),
        "fiscal_balance_pct_gdp": (-3.1, None), "fiscal_trend": ("Neutral", None), "debt_to_gdp": (89.0, None),
        "balance_sheet_trend": ("Neutral", None),
        "cpi_surprise": ("In-line", None), "gdp_surprise": ("Miss", None),
        "employment_surprise": ("In-line", None), "pmi_surprise": ("Miss", None),
        "surprise_policy_relevance": ("Medium", None),
        "priced_rate_change_12m_now": (-0.20, None), "priced_rate_change_12m_1m_ago": (-0.10, None),
        "geopolitical_impact": ("Neutral", None), "geopolitical_confidence": ("Medium", None),
    },
    "GBP": {
        "current_policy_rate": (4.00, None), "expected_rate_3m": (3.85, None),
        "expected_rate_6m": (3.60, None), "expected_rate_12m": (3.40, None),
        "policy_stance": ("Hawkish", None), "forward_guidance_tone": ("Balanced", None),
        "yield_2y": (4.00, 4.15), "yield_10y": (4.45, 4.35),
        "cpi_yoy": (3.4, 3.6), "inflation_target": (2.0, None), "wage_growth": (5.0, None),
        "inflation_expectation_10y": (2.5, 2.4),
        "unemployment_rate": (4.5, 4.4), "employment_growth_yoy": (0.4, None),
        "gdp_yoy": (1.1, 0.9), "retail_sales_yoy": (1.6, None),
        "manuf_pmi": (47.5, 47.0), "services_pmi": (52.0, 51.2), "consumer_confidence": (-18.0, None),
        "current_account_pct_gdp": (-2.9, None), "trade_balance_trend": ("Stable", None),
        "risk_environment": ("Neutral", None), "vix_level": (16.0, 14.5),
        "net_position_pct_oi": (6.0, None), "position_percentile": (48.0, None), "position_change_4w": (1.0, None),
        "reer_deviation_pct": (-2.0, None),
        "fiscal_balance_pct_gdp": (-4.4, None), "fiscal_trend": ("Tightening", None), "debt_to_gdp": (101.0, None),
        "balance_sheet_trend": ("Contracting", None),
        "cpi_surprise": ("Beat", None), "gdp_surprise": ("In-line", None),
        "employment_surprise": ("Miss", None), "pmi_surprise": ("In-line", None),
        "surprise_policy_relevance": ("Medium", None),
        "priced_rate_change_12m_now": (-0.60, None), "priced_rate_change_12m_1m_ago": (-0.60, None),
        "geopolitical_impact": ("Neutral", None), "geopolitical_confidence": ("Medium", None),
    },
    "JPY": {
        "current_policy_rate": (0.75, None), "expected_rate_3m": (0.85, None),
        "expected_rate_6m": (1.00, None), "expected_rate_12m": (1.15, None),
        "policy_stance": ("Hawkish", None), "forward_guidance_tone": ("Hawkish", None),
        "yield_2y": (0.85, 0.75), "yield_10y": (1.55, 1.45),
        "cpi_yoy": (2.7, 2.9), "inflation_target": (2.0, None), "wage_growth": (3.0, None),
        "inflation_expectation_10y": (1.4, 1.3),
        "unemployment_rate": (2.5, 2.5), "employment_growth_yoy": (0.5, None),
        "gdp_yoy": (0.8, 0.5), "retail_sales_yoy": (1.9, None),
        "manuf_pmi": (50.2, 49.6), "services_pmi": (51.5, 51.0), "consumer_confidence": (36.0, None),
        "current_account_pct_gdp": (4.0, None), "trade_balance_trend": ("Improving", None),
        "risk_environment": ("Neutral", None), "vix_level": (16.0, 14.5),
        "safe_haven_demand_signal": ("Moderate", None), "geopolitical_stress_level": ("Medium", None),
        "net_position_pct_oi": (-8.0, None), "position_percentile": (35.0, None), "position_change_4w": (4.0, None),
        "reer_deviation_pct": (-22.0, None),
        "fiscal_balance_pct_gdp": (-5.8, None), "fiscal_trend": ("Neutral", None), "debt_to_gdp": (255.0, None),
        "balance_sheet_trend": ("Contracting", None),
        "cpi_surprise": ("Beat", None), "gdp_surprise": ("Beat", None),
        "employment_surprise": ("In-line", None), "pmi_surprise": ("In-line", None),
        "surprise_policy_relevance": ("High", None),
        "priced_rate_change_12m_now": (0.40, None), "priced_rate_change_12m_1m_ago": (0.25, None),
        "geopolitical_impact": ("Neutral", None), "geopolitical_confidence": ("Medium", None),
    },
    "CHF": {
        "current_policy_rate": (0.25, None), "expected_rate_3m": (0.25, None),
        "expected_rate_6m": (0.25, None), "expected_rate_12m": (0.25, None),
        "policy_stance": ("Neutral", None), "forward_guidance_tone": ("Balanced", None),
        "yield_2y": (0.35, 0.40), "yield_10y": (0.65, 0.60),
        "cpi_yoy": (0.6, 0.5), "inflation_target": (1.0, None), "wage_growth": (1.6, None),
        "inflation_expectation_10y": (0.9, 0.9),
        "unemployment_rate": (2.6, 2.6), "employment_growth_yoy": (0.7, None),
        "gdp_yoy": (1.3, 1.1), "retail_sales_yoy": (0.8, None),
        "manuf_pmi": (49.0, 48.5), "services_pmi": (52.5, 52.0), "consumer_confidence": (-8.0, None),
        "current_account_pct_gdp": (6.5, None), "trade_balance_trend": ("Stable", None),
        "risk_environment": ("Neutral", None), "vix_level": (16.0, 14.5),
        "safe_haven_demand_signal": ("Strong", None), "geopolitical_stress_level": ("Medium", None),
        "net_position_pct_oi": (12.0, None), "position_percentile": (58.0, None), "position_change_4w": (2.0, None),
        "reer_deviation_pct": (15.0, None),
        "fiscal_balance_pct_gdp": (0.2, None), "fiscal_trend": ("Neutral", None), "debt_to_gdp": (39.0, None),
        "balance_sheet_trend": ("Neutral", None),
        "cpi_surprise": ("In-line", None), "gdp_surprise": ("In-line", None),
        "employment_surprise": ("In-line", None), "pmi_surprise": ("In-line", None),
        "surprise_policy_relevance": ("Low", None),
        "priced_rate_change_12m_now": (0.0, None), "priced_rate_change_12m_1m_ago": (0.0, None),
        "geopolitical_impact": ("Neutral", None), "geopolitical_confidence": ("Medium", None),
    },
    "CAD": {
        "current_policy_rate": (2.75, None), "expected_rate_3m": (2.75, None),
        "expected_rate_6m": (2.60, None), "expected_rate_12m": (2.50, None),
        "policy_stance": ("Neutral", None), "forward_guidance_tone": ("Balanced", None),
        "yield_2y": (2.80, 2.90), "yield_10y": (3.20, 3.15),
        "cpi_yoy": (2.0, 1.9), "inflation_target": (2.0, None), "wage_growth": (3.6, None),
        "inflation_expectation_10y": (2.1, 2.1),
        "unemployment_rate": (6.8, 6.7), "employment_growth_yoy": (0.9, None),
        "gdp_yoy": (1.2, 1.0), "retail_sales_yoy": (1.4, None),
        "manuf_pmi": (49.0, 48.3), "services_pmi": (50.5, 50.0), "consumer_confidence": (55.0, None),
        "current_account_pct_gdp": (-1.0, None), "trade_balance_trend": ("Stable", None),
        "commodity_price_change_3m": (6.0, None), "terms_of_trade_trend": ("Improving", None),
        "china_pmi": (49.8, None), "china_trajectory": ("Neutral", None),
        "risk_environment": ("Neutral", None), "vix_level": (16.0, 14.5),
        "net_position_pct_oi": (-5.0, None), "position_percentile": (40.0, None), "position_change_4w": (-1.0, None),
        "reer_deviation_pct": (-6.0, None),
        "fiscal_balance_pct_gdp": (-1.8, None), "fiscal_trend": ("Neutral", None), "debt_to_gdp": (68.0, None),
        "balance_sheet_trend": ("Neutral", None),
        "cpi_surprise": ("In-line", None), "gdp_surprise": ("Beat", None),
        "employment_surprise": ("Beat", None), "pmi_surprise": ("In-line", None),
        "surprise_policy_relevance": ("Medium", None),
        "priced_rate_change_12m_now": (-0.25, None), "priced_rate_change_12m_1m_ago": (-0.25, None),
        "geopolitical_impact": ("Neutral", None), "geopolitical_confidence": ("Medium", None),
    },
    "AUD": {
        "current_policy_rate": (3.85, None), "expected_rate_3m": (3.75, None),
        "expected_rate_6m": (3.60, None), "expected_rate_12m": (3.60, None),
        "policy_stance": ("Neutral", None), "forward_guidance_tone": ("Balanced", None),
        "yield_2y": (3.55, 3.65), "yield_10y": (4.30, 4.20),
        "cpi_yoy": (2.8, 3.0), "inflation_target": (2.5, None), "wage_growth": (3.5, None),
        "inflation_expectation_10y": (2.4, 2.4),
        "unemployment_rate": (4.2, 4.1), "employment_growth_yoy": (1.8, None),
        "gdp_yoy": (1.6, 1.3), "retail_sales_yoy": (2.2, None),
        "manuf_pmi": (49.8, 49.0), "services_pmi": (51.8, 51.0), "consumer_confidence": (86.0, None),
        "current_account_pct_gdp": (0.5, None), "trade_balance_trend": ("Improving", None),
        "commodity_price_change_3m": (9.0, None), "terms_of_trade_trend": ("Improving", None),
        "china_pmi": (49.8, None), "china_trajectory": ("Improving", None),
        "risk_environment": ("Moderate Risk-On", None), "vix_level": (14.5, 16.0),
        "net_position_pct_oi": (14.0, None), "position_percentile": (68.0, None), "position_change_4w": (6.0, None),
        "reer_deviation_pct": (-3.0, None),
        "fiscal_balance_pct_gdp": (-1.0, None), "fiscal_trend": ("Neutral", None), "debt_to_gdp": (35.0, None),
        "balance_sheet_trend": ("Neutral", None),
        "cpi_surprise": ("Beat", None), "gdp_surprise": ("In-line", None),
        "employment_surprise": ("Beat", None), "pmi_surprise": ("In-line", None),
        "surprise_policy_relevance": ("Medium", None),
        "priced_rate_change_12m_now": (-0.25, None), "priced_rate_change_12m_1m_ago": (-0.40, None),
        "geopolitical_impact": ("Neutral", None), "geopolitical_confidence": ("Medium", None),
    },
    "NZD": {
        "current_policy_rate": (2.75, None), "expected_rate_3m": (2.75, None),
        "expected_rate_6m": (2.75, None), "expected_rate_12m": (2.90, None),
        "policy_stance": ("Neutral", None), "forward_guidance_tone": ("Balanced", None),
        "yield_2y": (3.10, 3.20), "yield_10y": (4.40, 4.30),
        "cpi_yoy": (2.2, 2.5), "inflation_target": (2.0, None), "wage_growth": (3.0, None),
        "inflation_expectation_10y": (2.2, 2.2),
        "unemployment_rate": (5.1, 5.0), "employment_growth_yoy": (0.3, None),
        "gdp_yoy": (0.5, 0.2), "retail_sales_yoy": (0.6, None),
        "manuf_pmi": (48.5, 47.9), "services_pmi": (49.5, 49.0), "consumer_confidence": (92.0, None),
        "current_account_pct_gdp": (-5.5, None), "trade_balance_trend": ("Stable", None),
        "commodity_price_change_3m": (4.0, None), "terms_of_trade_trend": ("Stable", None),
        "china_pmi": (49.8, None), "china_trajectory": ("Improving", None),
        "risk_environment": ("Moderate Risk-On", None), "vix_level": (14.5, 16.0),
        "net_position_pct_oi": (-3.0, None), "position_percentile": (44.0, None), "position_change_4w": (2.0, None),
        "reer_deviation_pct": (-9.0, None),
        "fiscal_balance_pct_gdp": (-2.5, None), "fiscal_trend": ("Neutral", None), "debt_to_gdp": (43.0, None),
        "balance_sheet_trend": ("Neutral", None),
        "cpi_surprise": ("In-line", None), "gdp_surprise": ("Miss", None),
        "employment_surprise": ("Miss", None), "pmi_surprise": ("In-line", None),
        "surprise_policy_relevance": ("Medium", None),
        "priced_rate_change_12m_now": (0.10, None), "priced_rate_change_12m_1m_ago": (0.0, None),
        "geopolitical_impact": ("Neutral", None), "geopolitical_confidence": ("Medium", None),
    },
    "XAU": {
        "inflation_expectation_10y": (2.3, 2.2),
        "yield_10y": (4.20, 4.10),
        "risk_environment": ("Neutral", None), "vix_level": (16.0, 14.5),
        "safe_haven_demand_signal": ("Moderate", None), "geopolitical_stress_level": ("Medium", None),
        "etf_flows_trend": ("Inflows", None), "cb_gold_demand_trend": ("Strong", None),
        "net_position_pct_oi": (22.0, None), "position_percentile": (74.0, None), "position_change_4w": (3.0, None),
        "global_liquidity_trend": ("Neutral", None),
        "geopolitical_impact": ("Positive", None), "geopolitical_confidence": ("Medium", None),
    },
}


def load_sample_data(provider):
    for asset, fields in SAMPLE_VALUES.items():
        for field_key, (value, previous) in fields.items():
            fdef = FIELD_DEFS.get(field_key)
            if fdef is None or (fdef.assets is not None and asset not in fdef.assets):
                continue
            provider.set(asset, field_key, RawValue(
                value=value,
                previous_value=previous if fdef.has_previous else None,
                date=TODAY,
                source="Illustrative sample data",
                frequency=fdef.frequency,
                notes="Sample/demo value -- replace with real data.",
            ))
